import type { CustomerAccount, CustomerDossier, OperationEntry } from "./domain";

export const INITIAL_CUSTOMERS: CustomerAccount[] = [
  {
    domain: "alder-finch.example.test",
    health: "watch",
    id: "org_demo_01AF",
    initials: "AF",
    lastActive: "18 min ago",
    mrr: 24_500,
    name: "Alder & Finch Labs",
    openCases: 1,
    owner: "Elena Park",
    plan: "Enterprise",
    previousMrr: 23_100,
    renewalDate: "Sep 18, 2026",
    renewalDays: 36,
    seatsLimit: 120,
    seatsUsed: 82,
    status: "active",
  },
  {
    domain: "brightloop.example.test",
    health: "healthy",
    id: "org_demo_02BR",
    initials: "BR",
    lastActive: "1 hr ago",
    mrr: 8_750,
    name: "Brightloop Research",
    openCases: 0,
    owner: "Mika Rowan",
    plan: "Scale",
    previousMrr: 8_200,
    renewalDate: "Oct 12, 2026",
    renewalDays: 60,
    seatsLimit: 50,
    seatsUsed: 34,
    status: "active",
  },
  {
    domain: "cinderlane.example.test",
    health: "watch",
    id: "org_demo_03CS",
    initials: "CS",
    lastActive: "7 days ago",
    mrr: 2_400,
    name: "Cinderlane Systems",
    openCases: 2,
    owner: "Aisha Bell",
    plan: "Starter",
    previousMrr: 2_400,
    renewalDate: "Aug 25, 2026",
    renewalDays: 12,
    seatsLimit: 10,
    seatsUsed: 8,
    status: "active",
  },
  {
    domain: "dockside-metric.example.test",
    health: "healthy",
    id: "org_demo_04DM",
    initials: "DM",
    lastActive: "32 min ago",
    mrr: 31_000,
    name: "Dockside Metric",
    openCases: 1,
    owner: "Theo Moss",
    plan: "Enterprise",
    previousMrr: 28_500,
    renewalDate: "Nov 03, 2026",
    renewalDays: 82,
    seatsLimit: 150,
    seatsUsed: 121,
    status: "active",
  },
  {
    domain: "evervale.example.test",
    health: "risk",
    id: "org_demo_05ER",
    initials: "ER",
    lastActive: "14 days ago",
    mrr: 6_000,
    name: "Evervale Robotics",
    openCases: 3,
    owner: "Elena Park",
    plan: "Scale",
    previousMrr: 7_500,
    renewalDate: "Aug 19, 2026",
    renewalDays: 6,
    seatsLimit: 40,
    seatsUsed: 25,
    status: "active",
  },
  {
    domain: "fieldnote-cloud.example.test",
    health: "watch",
    id: "org_demo_06FC",
    initials: "FC",
    lastActive: "3 days ago",
    mrr: 1_800,
    name: "Fieldnote Cloud",
    openCases: 2,
    owner: "Mika Rowan",
    plan: "Starter",
    previousMrr: 1_800,
    renewalDate: "Trial",
    renewalDays: 9,
    seatsLimit: 10,
    seatsUsed: 6,
    status: "trial",
    trialDaysLeft: 9,
  },
  {
    domain: "glasswing.example.test",
    health: "healthy",
    id: "org_demo_07GD",
    initials: "GD",
    lastActive: "2 hr ago",
    mrr: 18_900,
    name: "Glasswing Data",
    openCases: 0,
    owner: "Theo Moss",
    plan: "Enterprise",
    previousMrr: 17_400,
    renewalDate: "Sep 01, 2026",
    renewalDays: 19,
    seatsLimit: 75,
    seatsUsed: 60,
    status: "active",
  },
  {
    domain: "harborlight.example.test",
    health: "healthy",
    id: "org_demo_08HO",
    initials: "HO",
    lastActive: "44 min ago",
    mrr: 7_250,
    name: "Harborlight Ops",
    openCases: 1,
    owner: "Aisha Bell",
    plan: "Scale",
    previousMrr: 6_800,
    renewalDate: "Oct 25, 2026",
    renewalDays: 73,
    seatsLimit: 40,
    seatsUsed: 28,
    status: "active",
  },
  {
    domain: "juniper-stack.example.test",
    health: "risk",
    id: "org_demo_09JS",
    initials: "JS",
    lastActive: "21 days ago",
    mrr: 27_500,
    name: "Juniper Stack",
    openCases: 4,
    owner: "Elena Park",
    plan: "Enterprise",
    previousMrr: 31_000,
    renewalDate: "Aug 16, 2026",
    renewalDays: 3,
    seatsLimit: 125,
    seatsUsed: 95,
    status: "active",
  },
  {
    domain: "kiteframe.example.test",
    health: "watch",
    id: "org_demo_10KS",
    initials: "KS",
    lastActive: "10 days ago",
    mrr: 2_000,
    name: "Kiteframe Studio",
    openCases: 0,
    owner: "Mika Rowan",
    plan: "Starter",
    previousMrr: 1_850,
    renewalDate: "Trial",
    renewalDays: 4,
    seatsLimit: 10,
    seatsUsed: 7,
    status: "trial",
    trialDaysLeft: 4,
  },
  {
    domain: "loomwell.example.test",
    health: "healthy",
    id: "org_demo_11LS",
    initials: "LS",
    lastActive: "5 hr ago",
    mrr: 9_550,
    name: "Loomwell Systems",
    openCases: 0,
    owner: "Theo Moss",
    plan: "Scale",
    previousMrr: 8_900,
    renewalDate: "Sep 30, 2026",
    renewalDays: 48,
    seatsLimit: 50,
    seatsUsed: 38,
    status: "active",
  },
  {
    domain: "mossbank.example.test",
    health: "risk",
    id: "org_demo_12MA",
    initials: "MA",
    lastActive: "28 days ago",
    mrr: 12_000,
    name: "Mossbank AI",
    openCases: 3,
    owner: "Aisha Bell",
    plan: "Scale",
    previousMrr: 14_000,
    renewalDate: "Sep 07, 2026",
    renewalDays: 25,
    seatsLimit: 60,
    seatsUsed: 57,
    status: "suspended",
  },
];

export const INITIAL_OPERATIONS: OperationEntry[] = [
  {
    actor: "Demo operator",
    id: "op-1",
    message: "Sample dossier created for Alder & Finch Labs",
    time: "10:15",
    tone: "positive",
  },
  {
    actor: "System",
    id: "op-2",
    message: "Juniper Stack moved to at risk",
    time: "09:42",
    tone: "warning",
  },
  {
    actor: "Billing simulator",
    id: "op-3",
    message: "Payment retry failed for Evervale Robotics",
    time: "08:54",
    tone: "danger",
  },
  {
    actor: "System",
    id: "op-4",
    message: "Seat threshold reached at Mossbank AI",
    time: "07:48",
    tone: "neutral",
  },
];

export const DEFAULT_DOSSIER: CustomerDossier = {
  company: "Alder & Finch Labs",
  domain: "alder-finch.example.test",
  health: "watch",
  mrr: 24_500,
  notes:
    "Synthetic sample: adoption is strong in the analytics team, while the operations group still needs an enablement session before renewal review.",
  organizationId: "org_demo_01AF",
  owner: "Elena Park",
  plan: "Enterprise",
  renewalDate: "September 18, 2026",
  risks: [
    {
      detail: "Operations workspace activity is down 24% over the last 30 days.",
      label: "Adoption drift",
      severity: "medium",
    },
    {
      detail: "Security review is open with two unanswered control questions.",
      label: "Security review",
      severity: "high",
    },
  ],
  seatsLimit: 120,
  seatsUsed: 82,
  stakeholders: [
    { email: "mina@alder-finch.example.test", name: "Mina Vale", role: "Executive sponsor" },
    { email: "rohan@alder-finch.example.test", name: "Rohan Pike", role: "Workspace admin" },
    { email: "elle@alder-finch.example.test", name: "Elle North", role: "Security lead" },
  ],
  timeline: [
    { date: "Aug 11", detail: "Eight operators completed the workflow lab.", title: "Enablement session" },
    { date: "Aug 07", detail: "Owner acknowledged the adoption drift signal.", title: "Health review" },
    { date: "Jul 29", detail: "Seat allocation increased from 100 to 120.", title: "Plan updated" },
  ],
};
